### ISSUE TITLE
miiteの例の動画を公開しませんか

### ISSUE THREAD

**Issue by yuuto1012227** [FUNProject14/miite#2]
実際動いてる様子を見せようにも，システムを外部公開していないのでなかなかに面倒ですよね．

幸いにも素晴らしいデモ動画を持っているので，URL限定公開とかでYoutubeにアップロードするとかしませんか．

**Comment by ejo090** [comment]
確かにそのとおりかもしれませんね。
思ったんですけど、Google Driveに動画があるし[これ](https://drive.google.com/file/d/0Bw9dv8Ak4HnkSXNnSDBRVzBQYUU/view?usp=sharing)で良いのではないでしょうか？

**Comment by ejo090** [comment]
なんかYoutubeのプレイヤーで再生されるのでちょうど良い感じします。

**Comment by yuuto1012227** [comment]
めちゃ便利ツールだ
限定共有だからリンク貼っても意味ないと思ってた

**Comment by ejo090** [comment]
先程貼ったURLで解決するかな？
あとはどこに貼るかだけども

**Comment by yuuto1012227** [comment]
俺の手元だと動画が見れない…

**Comment by ejo090** [comment]
そマ？

**Comment by yuuto1012227** [comment]
ブラウザをsafariからchromeに変えたら見れました

**Comment by ejo090** [comment]
環境依存なのはアレだからやはり動画をYoutubeとかにアップロードするのがいいのだろうか

**Comment by tos-kamiya** [comment]
やっぱyoutubeですよね。ニコ動だとアカウント持ってない人も多いだろうし

**Comment by ejo090** [comment]
そうですね。アカウントはどうしましょうか…。

**Comment by yuuto1012227** [comment]
妥当なのはプロジェクト14公式(?)アカウントを作ることだよねえ

**Comment by ejo090** [comment]
まぁそうなりますよね…。プロジェクト14公式のアカウントというよりmiiteっぽいアカウントの方がいいかもしれない

**Comment by tos-kamiya** [comment]
おそらくfun-project14としといたほうが、学校のプロジェクトと結びつくような気がしますけどね。miiteブランドでたくさん動画を上げるというのならmiiteっぽいアカウントかなあ。

**Comment by ejo090** [comment]
それだと来年再来年にproject14になるグループ(どこだかわからないけど)とカブっちゃうんじゃないかなぁと思ったんですよね。そのへん問題無さそうならfun-project14とかでいいかもって感じですね。

**Comment by tos-kamiya** [comment]
youtubeでもgithubでも、fun-project的なアカウントはほとんどないので、かぶるのは気にしなくても良いと思います。あとは、fun-project14的な名前でもよいし、miite作ってますチーム的な名前でもよいし、全く別の名前でもよいです。学校のプロジェクト学習との関係を特に打ち出したくないということであれば、fun-なんたらじゃないほうがいいかもしれませんね。

**Comment by ejo090** [comment]
いちれんさんがいまfunproject14的なアカウントを作成しています。

**Comment by ichiren1** [comment]
https://www.youtube.com/watch?v=aNCbeOaOfuQ
です

**Comment by ejo090** [comment]
とりあえず例の動画が公開されたのでissue閉じます。
